"""Fill the metrics block in README.md from the report files.

Usage:
    python -m tweet_emotion.sync_readme            rewrite the block
    python -m tweet_emotion.sync_readme --check    exit 1 when the block would change

README.md holds one block between <!-- metrics:start --> and <!-- metrics:end -->. The block is
rendered from reports/metrics.json, reports/loadtest.json, and models/version.json. A missing file
renders [todo] for every field it would have filled, so no number is ever typed by hand. Running
the command twice changes nothing.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tweet_emotion import settings

START = "<!-- metrics:start -->"
END = "<!-- metrics:end -->"
TODO = "[todo]"
GENERATED_NOTE = (
    "<!-- Generated by python -m tweet_emotion.sync_readme from reports/*.json and "
    "models/version.json. Edit those files, not this block. -->"
)
SHA_SHORT_LENGTH = 12
COMMAND = "python -m tweet_emotion.sync_readme"

SOURCES: dict[str, str] = {
    "metrics": "reports/metrics.json",
    "loadtest": "reports/loadtest.json",
    "version": "models/version.json",
}

# Human names for the candidate keys in params.yaml. Unknown keys render as themselves.
CANDIDATE_LABELS: dict[str, str] = {
    "logreg": "Logistic regression",
    "nb": "Multinomial naive Bayes",
    "xgboost": "XGBoost",
}

# Human names for the selection metric in params.yaml. Unknown keys render as themselves.
METRIC_LABELS: dict[str, str] = {
    "roc_auc": "ROC-AUC",
    "accuracy": "accuracy",
    "f1": "F1",
}


# ---------------------------------------------------------------------------
# Receipts
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Receipts:
    """The three source documents; any of them may be None when its file is absent."""

    metrics: dict | None
    loadtest: dict | None
    version: dict | None

    def get(self, source: str, *keys: str) -> Any:
        """Walk nested keys; None when the source or any key is missing."""
        node: Any = getattr(self, source)
        for key in keys:
            if not isinstance(node, dict) or key not in node:
                return None
            node = node[key]
        return node

    def first(self, *paths: tuple[str, ...]) -> Any:
        """The first path that resolves to a value; None when none of them does."""
        for path in paths:
            value = self.get(*path)
            if value is not None:
                return value
        return None

    def missing(self) -> list[str]:
        return [path for name, path in SOURCES.items() if getattr(self, name) is None]


def read_json_optional(path: Path) -> dict | None:
    """The JSON object at ``path``; None when the file is absent, unreadable, or not an object."""
    if not path.is_file():
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
    except (OSError, ValueError) as exc:
        print(f"note: {path.name} could not be read ({exc}); its fields render as {TODO}")
        return None
    return doc if isinstance(doc, dict) else None


def load_receipts(root: Path) -> Receipts:
    return Receipts(
        metrics=read_json_optional(root / SOURCES["metrics"]),
        loadtest=read_json_optional(root / SOURCES["loadtest"]),
        version=read_json_optional(root / SOURCES["version"]),
    )


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------


def is_number(value: Any) -> bool:
    return isinstance(value, int | float) and not isinstance(value, bool)


def f4(value: Any) -> str:
    """Metrics: four decimals."""
    return f"{value:.4f}" if is_number(value) else TODO


def f2(value: Any) -> str:
    """Latency in milliseconds, throughput, fit seconds, and thresholds: two decimals."""
    return f"{value:.2f}" if is_number(value) else TODO


def fint(value: Any) -> str:
    """Counts: integers with thousands separators."""
    return f"{int(value):,}" if is_number(value) else TODO


def ftext(value: Any) -> str:
    return str(value) if isinstance(value, str) and value else TODO


def fshort(value: Any, length: int = SHA_SHORT_LENGTH) -> str:
    return value[:length] if isinstance(value, str) and value else TODO


def fpm(mean: Any, std: Any) -> str:
    """A cross-validation score as 'mean ± std', four decimals each."""
    return f"{f4(mean)} ± {f4(std)}"


def candidate_label(name: Any) -> str:
    """'Logistic regression (`logreg`)' for a known key, the key itself otherwise."""
    if not isinstance(name, str) or not name:
        return TODO
    label = CANDIDATE_LABELS.get(name)
    return f"{label} (`{name}`)" if label else f"`{name}`"


def metric_label(name: Any) -> str:
    if not isinstance(name, str) or not name:
        return TODO
    return METRIC_LABELS.get(name, name)


def model_label(receipts: Receipts) -> str:
    """The shipped model's human name, from version.json first and metrics.json second."""
    name = receipts.first(("version", "model"), ("metrics", "model"))
    if not isinstance(name, str) or not name:
        return TODO
    return CANDIDATE_LABELS.get(name, name)


def candidates(receipts: Receipts) -> dict[str, Any]:
    """The per-candidate cv dicts, in params order; metrics.json first, version.json second."""
    doc = receipts.first(("metrics", "candidates_cv"), ("version", "candidates"))
    return doc if isinstance(doc, dict) and doc else {}


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------


def render_results_table(r: Receipts) -> list[str]:
    """Held-out metrics of the shipped model next to the majority-class baseline."""
    m = "metrics"
    return [
        f"| Metric | {model_label(r)} (this model) | Majority baseline |",
        "|---|---|---|",
        f"| Accuracy | {f4(r.get(m, 'accuracy'))} | {f4(r.get(m, 'majority_baseline_accuracy'))} |",
        f"| Precision | {f4(r.get(m, 'precision'))} | |",
        f"| Recall | {f4(r.get(m, 'recall'))} | |",
        f"| F1 | {f4(r.get(m, 'f1'))} | |",
        f"| ROC-AUC | {f4(r.get(m, 'roc_auc'))} | |",
        f"| PR-AUC (average precision) | {f4(r.get(m, 'pr_auc'))} | |",
        f"| Brier score (lower is better) | {f4(r.get(m, 'brier'))} | |",
        f"| Log loss (lower is better) | {f4(r.get(m, 'log_loss'))} | |",
    ]


def render_candidates_table(r: Receipts) -> list[str]:
    """One row per candidate from the cross-validation record, the shipped one marked."""
    winner = r.first(("version", "model"), ("metrics", "model"))
    header = [
        "| Candidate | cv ROC-AUC (mean ± std) | cv accuracy | Fit seconds | Shipped |",
        "|---|---|---|---|---|",
    ]
    rows: list[str] = []
    for name, cv in candidates(r).items():
        record: dict[str, Any] = cv if isinstance(cv, dict) else {}
        shipped = "yes " if name == winner else ""
        rows.append(
            f"| {candidate_label(name)} | "
            f"{fpm(record.get('cv_roc_auc_mean'), record.get('cv_roc_auc_std'))} | "
            f"{f4(record.get('cv_accuracy_mean'))} | {f2(record.get('fit_seconds'))} | "
            f"{shipped}|"
        )
    if not rows:
        rows.append(f"| {TODO} | {TODO} | {TODO} | {TODO} | |")
    return header + rows


def render_readme(r: Receipts) -> str:
    """Results table, candidates table, then the latency and provenance lines."""
    m = "metrics"
    folds = fint(r.get("version", "cv_folds"))
    selection = metric_label(r.first(("version", "selection_metric"), (m, "selection_metric")))
    lines = [
        GENERATED_NOTE,
        f"Held-out test split, n = {fint(r.get(m, 'n_test'))}, share labelled "
        f"{ftext(r.get(m, 'positive_label'))} {f4(r.get(m, 'positive_rate_test'))}, decision "
        f"threshold {f2(r.get(m, 'threshold'))}. Nothing below was tuned on it.",
        "",
        *render_results_table(r),
        "",
        "The majority baseline predicts the more common class for every tweet, so only its "
        "accuracy is meaningful.",
        "",
        f"Candidates, {folds}-fold stratified cross-validation on the training split only, "
        f"selected by cv {selection} (models/version.json):",
        "",
        *render_candidates_table(r),
        "",
        f"Latency: p95 {f2(r.get('loadtest', 'p95_ms'))} ms for POST /predict, "
        f"{fint(r.get('loadtest', 'requests'))} requests at concurrency "
        f"{fint(r.get('loadtest', 'concurrency'))}, {f2(r.get('loadtest', 'rps'))} requests per "
        f"second, on {ftext(r.get('loadtest', 'host'))} (reports/loadtest.json).",
        "",
        f"Provenance: trained {ftext(r.first(('version', 'trained_at'), (m, 'trained_at')))}, "
        f"git {ftext(r.get('version', 'git_sha_short'))}, data sha256 "
        f"{fshort(r.first(('version', 'data_sha256'), (m, 'data_sha256')))}, rows "
        f"{fint(r.first((m, 'n_train'), ('version', 'n_train')))} train / "
        f"{fint(r.get(m, 'n_test'))} test (models/version.json).",
    ]
    return "\n".join(lines)


TARGETS: dict[str, Callable[[Receipts], str]] = {
    "README.md": render_readme,
}


# ---------------------------------------------------------------------------
# Block replacement
# ---------------------------------------------------------------------------


def replace_block(text: str, block: str) -> str:
    """Swap the content between the markers; the markers themselves stay on their own lines."""
    if text.count(START) != 1 or text.count(END) != 1:
        raise ValueError(f"expected exactly one {START} and one {END}")
    start = text.index(START) + len(START)
    end = text.index(END)
    if end < start:
        raise ValueError(f"{END} appears before {START}")
    return f"{text[:start]}\n{block}\n{text[end:]}"


def sync(
    root: Path,
    check: bool,
    targets: dict[str, Callable[[Receipts], str]] | None = None,
    command: str = COMMAND,
) -> int:
    """Rewrite (or, with check, only compare) every target. Returns the exit code.

    ``targets`` maps a path relative to ``root`` to the function that renders its block;
    ``command`` names the command a stale file should be fixed with.
    """
    receipts = load_receipts(root)
    for path in receipts.missing():
        print(f"note: {path} is missing; its fields render as {TODO}")

    stale: list[str] = []
    for relative, render in (targets or TARGETS).items():
        path = root / relative
        if not path.is_file():
            print(f"note: {relative} is absent here; skipped")
            continue
        raw = path.read_bytes().decode("utf-8")
        try:
            updated = replace_block(raw.replace("\r\n", "\n"), render(receipts))
        except ValueError as exc:
            print(f"error: {relative}: {exc}", file=sys.stderr)
            return 2
        if updated == raw:
            print(f"unchanged  {relative}")
            continue
        stale.append(relative)
        if check:
            print(f"stale      {relative}")
        else:
            path.write_bytes(updated.encode("utf-8"))
            print(f"updated    {relative}")

    if check and stale:
        print(f"{len(stale)} file(s) would change; run {command}", file=sys.stderr)
        return 1
    return 0


def build_parser(prog: str, description: str) -> argparse.ArgumentParser:
    """The shared command line: --check and --root."""
    parser = argparse.ArgumentParser(prog=prog, description=description)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the block differs from what the reports render, write nothing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=settings.REPO_ROOT,
        help="repository root (default: the folder holding params.yaml)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser(
        prog=COMMAND,
        description="Fill the metrics block in README.md from the reports.",
    )
    args = parser.parse_args(argv)
    return sync(args.root.resolve(), args.check)


if __name__ == "__main__":
    sys.exit(main())
